/**
 * @alecrae/ai-engine — Phishing Protection with Explainer (B6)
 *
 * Multi-signal phishing analyser that emits a structured indicator list AND
 * a single human-readable explanation sentence (generated by Claude Sonnet)
 * the UI can show inline. Built on top of B5's SenderVerification.
 */

import Anthropic from "@anthropic-ai/sdk";
import type { SenderVerification } from "./sender-verify.js";

// ─── Types ───────────────────────────────────────────────────────────────────

export type PhishingIndicatorType =
  | "sender_reply_mismatch"
  | "display_name_spoof"
  | "url_domain_mismatch"
  | "urgency_language"
  | "credential_harvest"
  | "new_domain"
  | "lookalike_domain"
  | "homograph_attack"
  | "suspicious_attachment"
  | "auth_failed"
  | "free_provider_brand_claim";

export type PhishingSeverity = "info" | "low" | "medium" | "high" | "critical";

export interface PhishingIndicator {
  readonly type: PhishingIndicatorType;
  readonly severity: PhishingSeverity;
  readonly evidence: string;
  readonly explanation: string;
}

export type PhishingRiskLevel =
  | "safe"
  | "low"
  | "medium"
  | "high"
  | "critical";

export type PhishingSuggestedAction =
  | "delete"
  | "report"
  | "verify_sender"
  | "safe_to_open";

export interface PhishingLink {
  readonly href: string;
  readonly text?: string;
}

export interface PhishingAttachment {
  readonly filename: string;
  readonly contentType: string;
  readonly size: number;
}

export interface PhishingInput {
  readonly from: string;
  readonly replyTo?: string;
  readonly subject: string;
  readonly body: string;
  readonly links: readonly PhishingLink[];
  readonly headers: Record<string, string>;
  readonly senderVerification: SenderVerification;
  readonly attachments?: readonly PhishingAttachment[];
}

export interface PhishingAnalysis {
  readonly riskLevel: PhishingRiskLevel;
  readonly riskScore: number;
  readonly isPhishing: boolean;
  readonly indicators: readonly PhishingIndicator[];
  readonly explanation: string;
  readonly suggestedActions: readonly PhishingSuggestedAction[];
}

// ─── Brand registry (for lookalike detection) ────────────────────────────────

const BRANDS: ReadonlyMap<string, readonly string[]> = new Map([
  ["paypal", ["paypal.com"]],
  ["apple", ["apple.com", "icloud.com"]],
  ["google", ["google.com", "gmail.com"]],
  ["microsoft", ["microsoft.com", "outlook.com", "office.com", "live.com"]],
  ["amazon", ["amazon.com", "aws.amazon.com"]],
  ["netflix", ["netflix.com"]],
  ["facebook", ["facebook.com", "meta.com"]],
  ["instagram", ["instagram.com"]],
  ["chase", ["chase.com"]],
  ["wellsfargo", ["wellsfargo.com"]],
  ["bankofamerica", ["bankofamerica.com"]],
  ["dropbox", ["dropbox.com"]],
  ["github", ["github.com"]],
  ["stripe", ["stripe.com"]],
  ["linkedin", ["linkedin.com"]],
  ["docusign", ["docusign.com"]],
]);

const DANGEROUS_EXTENSIONS: ReadonlySet<string> = new Set([
  ".exe", ".scr", ".bat", ".cmd", ".com", ".pif", ".msi", ".vbs",
  ".js", ".jse", ".wsf", ".ps1", ".jar", ".hta", ".lnk", ".iso",
  ".docm", ".xlsm", ".pptm",
]);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  let prev = new Array<number>(n + 1);
  let curr = new Array<number>(n + 1);
  for (let j = 0; j <= n; j++) prev[j] = j;
  for (let i = 1; i <= m; i++) {
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(
        (prev[j] ?? 0) + 1,
        (curr[j - 1] ?? 0) + 1,
        (prev[j - 1] ?? 0) + cost,
      );
    }
    [prev, curr] = [curr, prev];
  }
  return prev[n] ?? 0;
}

function extractAddress(addr: string): { display: string; email: string; domain: string } {
  const trimmed = addr.trim();
  const angle = /^(.*)<([^>]+)>\s*$/.exec(trimmed);
  let display = "";
  let email = trimmed;
  if (angle) {
    display = (angle[1] ?? "").trim().replace(/^"|"$/g, "");
    email = (angle[2] ?? "").trim();
  }
  const at = email.lastIndexOf("@");
  const domain = at >= 0 ? email.slice(at + 1).toLowerCase() : "";
  return { display, email: email.toLowerCase(), domain };
}

function getRegistrableBase(host: string): string {
  const parts = host.split(".");
  if (parts.length < 2) return host;
  return parts.slice(-2).join(".");
}

function containsNonAscii(s: string): boolean {
  // eslint-disable-next-line no-control-regex
  return /[^\x00-\x7f]/.test(s);
}

function getExtension(filename: string): string | null {
  const m = filename.toLowerCase().match(/(\.[a-z0-9]+)$/);
  return m && m[1] ? m[1] : null;
}

// ─── Detection passes ────────────────────────────────────────────────────────

function detectSenderReplyMismatch(input: PhishingInput): PhishingIndicator | null {
  if (!input.replyTo) return null;
  const fromInfo = extractAddress(input.from);
  const replyInfo = extractAddress(input.replyTo);
  if (!replyInfo.domain || !fromInfo.domain) return null;
  if (replyInfo.domain === fromInfo.domain) return null;
  // Same registrable base is fine (e.g. github.com vs noreply.github.com).
  if (getRegistrableBase(replyInfo.domain) === getRegistrableBase(fromInfo.domain)) return null;
  return {
    type: "sender_reply_mismatch",
    severity: "high",
    evidence: `From: ${fromInfo.domain} / Reply-To: ${replyInfo.domain}`,
    explanation: `Replies will be sent to ${replyInfo.domain}, which is a different domain than the sender ${fromInfo.domain}.`,
  };
}

function detectDisplayNameSpoof(input: PhishingInput): PhishingIndicator | null {
  const { display, domain } = extractAddress(input.from);
  if (!display || !domain) return null;
  const displayLower = display.toLowerCase();
  for (const [brand, brandDomains] of BRANDS) {
    if (displayLower.includes(brand)) {
      const matchesBrand = brandDomains.some(
        (bd) => domain === bd || domain.endsWith(`.${bd}`),
      );
      if (!matchesBrand) {
        return {
          type: "display_name_spoof",
          severity: "critical",
          evidence: `Display name "${display}" claims ${brand} but sent from ${domain}`,
          explanation: `The display name impersonates ${brand}, but the email actually comes from ${domain}, which is not an official ${brand} domain.`,
        };
      }
    }
  }
  return null;
}

function detectUrlMismatch(input: PhishingInput): PhishingIndicator[] {
  const indicators: PhishingIndicator[] = [];
  for (const link of input.links) {
    let parsed: URL;
    try {
      parsed = new URL(link.href);
    } catch {
      continue;
    }
    const actualHost = parsed.hostname.toLowerCase();
    const text = (link.text ?? "").trim().toLowerCase();
    if (!text) continue;
    if (!/^(https?:\/\/)?[a-z0-9.-]+\.[a-z]{2,}/i.test(text)) continue;
    let textHost: string;
    try {
      textHost = new URL(text.startsWith("http") ? text : `https://${text}`)
        .hostname.toLowerCase();
    } catch {
      continue;
    }
    if (textHost !== actualHost && getRegistrableBase(textHost) !== getRegistrableBase(actualHost)) {
      indicators.push({
        type: "url_domain_mismatch",
        severity: "critical",
        evidence: `Link text "${link.text}" → ${actualHost}`,
        explanation: `A link displays "${link.text}" but actually points to ${actualHost}.`,
      });
    }
  }
  return indicators;
}

const URGENCY_PATTERNS: readonly RegExp[] = [
  /your account will be (suspended|locked|closed|terminated|deleted)/i,
  /immediate(ly)? (action|attention|response)/i,
  /within \d+ (hours?|days?|minutes?)/i,
  /final (notice|warning|reminder)/i,
  /failure to (respond|comply|verify)/i,
  /urgent(ly)?/i,
];

function detectUrgency(input: PhishingInput): PhishingIndicator | null {
  const text = `${input.subject}\n${input.body}`;
  for (const re of URGENCY_PATTERNS) {
    const m = re.exec(text);
    if (m) {
      return {
        type: "urgency_language",
        severity: "medium",
        evidence: m[0],
        explanation: `The message uses urgency language ("${m[0]}") to pressure you into acting without thinking.`,
      };
    }
  }
  return null;
}

const CREDENTIAL_PATTERNS: readonly RegExp[] = [
  /verify\s+your\s+(account|identity|password|email)/i,
  /confirm\s+your\s+(identity|password|account)/i,
  /(re)?enter\s+your\s+(password|credentials|login)/i,
  /update\s+your\s+(payment|billing|credit\s+card)/i,
  /sign\s+in\s+to\s+(restore|continue|verify)/i,
];

function detectCredentialHarvest(input: PhishingInput): PhishingIndicator | null {
  const text = `${input.subject}\n${input.body}`;
  for (const re of CREDENTIAL_PATTERNS) {
    const m = re.exec(text);
    if (m) {
      return {
        type: "credential_harvest",
        severity: "high",
        evidence: m[0],
        explanation: `The message asks you to "${m[0]}", a common credential-harvesting pattern.`,
      };
    }
  }
  return null;
}

function detectNewDomain(input: PhishingInput): PhishingIndicator | null {
  const age = input.senderVerification.domainAge;
  if (age === null) return null;
  if (age >= 30) return null;
  return {
    type: "new_domain",
    severity: age < 7 ? "high" : "medium",
    evidence: `Domain age: ${age} day${age === 1 ? "" : "s"}`,
    explanation: `The sender's domain was registered ${age} day${age === 1 ? "" : "s"} ago, which is unusual for a legitimate organisation.`,
  };
}

function detectLookalikeDomain(input: PhishingInput): PhishingIndicator | null {
  const { domain } = extractAddress(input.from);
  if (!domain) return null;
  const base = (domain.split(".")[0] ?? "").toLowerCase();
  if (base.length < 3) return null;
  for (const [brand, brandDomains] of BRANDS) {
    if (brandDomains.some((d) => domain === d || domain.endsWith(`.${d}`))) return null;
    const distance = levenshtein(base, brand);
    if (distance > 0 && distance <= 2) {
      return {
        type: "lookalike_domain",
        severity: "critical",
        evidence: `${domain} ≈ ${brand} (Levenshtein distance ${distance})`,
        explanation: `The sender's domain "${domain}" is only ${distance} character${distance === 1 ? "" : "s"} away from the legitimate ${brand} domain.`,
      };
    }
    if (base.includes(brand) && base !== brand) {
      return {
        type: "lookalike_domain",
        severity: "high",
        evidence: `${domain} contains "${brand}"`,
        explanation: `The sender's domain "${domain}" contains the brand name "${brand}" but is not an official ${brand} domain.`,
      };
    }
  }
  return null;
}

function detectHomographAttack(input: PhishingInput): PhishingIndicator | null {
  const { domain } = extractAddress(input.from);
  if (!domain) return null;
  if (domain.startsWith("xn--") || domain.includes(".xn--") || containsNonAscii(domain)) {
    return {
      type: "homograph_attack",
      severity: "critical",
      evidence: `Domain contains internationalised characters: ${domain}`,
      explanation: `The sender's domain uses internationalised (Punycode/Unicode) characters, a known homograph attack technique used to impersonate legitimate brands.`,
    };
  }
  return null;
}

function detectSuspiciousAttachments(input: PhishingInput): PhishingIndicator[] {
  const out: PhishingIndicator[] = [];
  for (const att of input.attachments ?? []) {
    const ext = getExtension(att.filename);
    if (ext && DANGEROUS_EXTENSIONS.has(ext)) {
      out.push({
        type: "suspicious_attachment",
        severity: ext === ".exe" || ext === ".scr" || ext === ".js" ? "critical" : "high",
        evidence: `${att.filename} (${att.contentType})`,
        explanation: `The attachment "${att.filename}" uses the ${ext} format, which can execute code on your machine.`,
      });
    }
    if (/\.\w{2,4}\.(exe|scr|bat|cmd|com|pif|vbs|js|ps1)$/i.test(att.filename)) {
      out.push({
        type: "suspicious_attachment",
        severity: "critical",
        evidence: `${att.filename} has a double extension`,
        explanation: `The attachment "${att.filename}" uses a double extension, a classic malware disguise technique.`,
      });
    }
  }
  return out;
}

function detectAuthFailures(input: PhishingInput): PhishingIndicator | null {
  const v = input.senderVerification;
  const failures: string[] = [];
  if (!v.spfPass) failures.push("SPF");
  if (!v.dkimPass) failures.push("DKIM");
  if (!v.dmarcPass) failures.push("DMARC");
  if (failures.length === 0) return null;
  if (failures.length < 2) {
    return {
      type: "auth_failed",
      severity: "low",
      evidence: `${failures.join(", ")} did not pass`,
      explanation: `${failures.join(", ")} authentication did not pass for this email.`,
    };
  }
  return {
    type: "auth_failed",
    severity: failures.length === 3 ? "high" : "medium",
    evidence: `${failures.join(", ")} failed`,
    explanation: `${failures.join(", ")} authentication failed, meaning the email cannot be cryptographically tied to the claimed sender.`,
  };
}

function detectFreeProviderBrandClaim(input: PhishingInput): PhishingIndicator | null {
  const v = input.senderVerification;
  if (!v.isFreeEmailProvider) return null;
  const display = extractAddress(input.from).display.toLowerCase();
  for (const brand of BRANDS.keys()) {
    if (display.includes(brand)) {
      return {
        type: "free_provider_brand_claim",
        severity: "high",
        evidence: `Free provider ${v.domain} with display name claiming ${brand}`,
        explanation: `The email claims to be from ${brand} but was sent from a free email provider (${v.domain}).`,
      };
    }
  }
  return null;
}

// ─── Scoring ─────────────────────────────────────────────────────────────────

const SEVERITY_WEIGHTS: Record<PhishingSeverity, number> = {
  info: 2,
  low: 8,
  medium: 18,
  high: 32,
  critical: 55,
};

function scoreIndicators(indicators: readonly PhishingIndicator[]): number {
  let score = 0;
  for (const ind of indicators) {
    score += SEVERITY_WEIGHTS[ind.severity];
  }
  return Math.min(100, score);
}

function deriveRiskLevel(score: number): PhishingRiskLevel {
  if (score >= 80) return "critical";
  if (score >= 55) return "high";
  if (score >= 30) return "medium";
  if (score >= 10) return "low";
  return "safe";
}

function deriveActions(
  level: PhishingRiskLevel,
  indicators: readonly PhishingIndicator[],
): PhishingSuggestedAction[] {
  const hasCritical = indicators.some((i) => i.severity === "critical");
  if (level === "critical" || hasCritical) return ["delete", "report"];
  if (level === "high") return ["report", "verify_sender"];
  if (level === "medium") return ["verify_sender"];
  if (level === "low") return ["verify_sender"];
  return ["safe_to_open"];
}

// ─── Claude Sonnet explanation generator ─────────────────────────────────────

const SONNET_MODEL = "claude-sonnet-4-6";

let cachedClient: Anthropic | null = null;
function getClient(): Anthropic {
  if (cachedClient) return cachedClient;
  const apiKey = process.env["ANTHROPIC_API_KEY"];
  if (!apiKey) {
    throw new Error(
      "ANTHROPIC_API_KEY is not set — phishing explanations are unavailable",
    );
  }
  cachedClient = new Anthropic({ apiKey });
  return cachedClient;
}

function buildFallbackExplanation(
  indicators: readonly PhishingIndicator[],
  level: PhishingRiskLevel,
): string {
  if (indicators.length === 0) {
    return "No phishing indicators were detected; this email appears to be safe to open.";
  }
  const top = [...indicators]
    .sort(
      (a, b) =>
        SEVERITY_WEIGHTS[b.severity] - SEVERITY_WEIGHTS[a.severity],
    )
    .slice(0, 3);
  const reasons = top.map((i) => i.explanation).join(" ");
  return `This email is rated ${level} risk. ${reasons}`;
}

async function generateExplanation(
  input: PhishingInput,
  indicators: readonly PhishingIndicator[],
  level: PhishingRiskLevel,
  score: number,
): Promise<string> {
  if (indicators.length === 0) {
    return "No phishing indicators were detected; this email appears to be safe to open.";
  }
  let client: Anthropic;
  try {
    client = getClient();
  } catch {
    return buildFallbackExplanation(indicators, level);
  }

  const indicatorLines = indicators
    .map(
      (i) =>
        `- [${i.severity}] ${i.type}: ${i.evidence} — ${i.explanation}`,
    )
    .join("\n");

  const v = input.senderVerification;
  const fromInfo = extractAddress(input.from);

  const prompt = [
    "You are AlecRae's phishing explainer. The user's inbox detected the",
    "following indicators on an incoming email. Write ONE short paragraph",
    "(2-4 sentences) in plain English explaining WHY this email is suspicious",
    "and what the user should be careful of. Be concrete: reference the actual",
    "sender, domain, and the strongest evidence. Do not invent facts.",
    "",
    `Email subject: ${input.subject}`,
    `From: ${input.from}`,
    `Sender domain: ${fromInfo.domain || v.domain}`,
    `Sender domain age: ${v.domainAge === null ? "unknown" : `${v.domainAge} days`}`,
    `Sender trust level: ${v.trustLevel}`,
    `Computed phishing risk: ${level} (${score}/100)`,
    "",
    "Indicators:",
    indicatorLines,
    "",
    "Respond with the paragraph only — no preamble, no JSON, no lists.",
  ].join("\n");

  try {
    const message = await client.messages.create({
      model: SONNET_MODEL,
      max_tokens: 400,
      temperature: 0.2,
      system:
        "You are a precise security analyst. You explain phishing risks " +
        "to non-technical users in clear, calm, factual language. Never " +
        "use markdown, never invent evidence, never fearmonger.",
      messages: [{ role: "user", content: prompt }],
    });
    const text = message.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();
    if (!text) return buildFallbackExplanation(indicators, level);
    return text;
  } catch {
    return buildFallbackExplanation(indicators, level);
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function analyzePhishing(
  input: PhishingInput,
): Promise<PhishingAnalysis> {
  const indicators: PhishingIndicator[] = [];

  const senderReply = detectSenderReplyMismatch(input);
  if (senderReply) indicators.push(senderReply);

  const displaySpoof = detectDisplayNameSpoof(input);
  if (displaySpoof) indicators.push(displaySpoof);

  indicators.push(...detectUrlMismatch(input));

  const urgency = detectUrgency(input);
  if (urgency) indicators.push(urgency);

  const credHarvest = detectCredentialHarvest(input);
  if (credHarvest) indicators.push(credHarvest);

  const newDomain = detectNewDomain(input);
  if (newDomain) indicators.push(newDomain);

  const lookalike = detectLookalikeDomain(input);
  if (lookalike) indicators.push(lookalike);

  const homograph = detectHomographAttack(input);
  if (homograph) indicators.push(homograph);

  indicators.push(...detectSuspiciousAttachments(input));

  const authFail = detectAuthFailures(input);
  if (authFail) indicators.push(authFail);

  const freeBrand = detectFreeProviderBrandClaim(input);
  if (freeBrand) indicators.push(freeBrand);

  const riskScore = scoreIndicators(indicators);
  const riskLevel = deriveRiskLevel(riskScore);
  const isPhishing = riskScore >= 55;
  const explanation = await generateExplanation(
    input,
    indicators,
    riskLevel,
    riskScore,
  );
  const suggestedActions = deriveActions(riskLevel, indicators);

  return {
    riskLevel,
    riskScore,
    isPhishing,
    indicators,
    explanation,
    suggestedActions,
  };
}

export const __internal = {
  levenshtein,
  extractAddress,
  scoreIndicators,
  deriveRiskLevel,
  deriveActions,
  buildFallbackExplanation,
};
