import {
  pgTable,
  text,
  timestamp,
  boolean,
  real,
  jsonb,
  index,
  uniqueIndex,
  pgEnum,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { accounts } from "./users.js";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const urgencyLevelEnum = pgEnum("urgency_level", [
  "critical",
  "high",
  "medium",
  "low",
  "none",
]);

export const emailSentimentEnum = pgEnum("email_sentiment", [
  "positive",
  "negative",
  "neutral",
  "urgent",
  "angry",
  "grateful",
  "confused",
]);

// ---------------------------------------------------------------------------
// Types for JSONB columns
// ---------------------------------------------------------------------------

/** Signals extracted from email content for priority scoring. */
export interface ContentSignals {
  hasDeadline: boolean;
  hasQuestion: boolean;
  hasMoneyConcern: boolean;
  hasActionRequired: boolean;
  mentionsAttachment: boolean;
  isReplyChain: boolean;
  threadLength: number;
}

/** A single smart reply option generated by AI. */
export interface SmartReplyOption {
  text: string;
  confidence: number;
  tone: string;
}

/** A single writing coach suggestion. */
export interface WritingCoachSuggestion {
  type: string;
  original: string;
  suggested: string;
  reason: string;
}

// ---------------------------------------------------------------------------
// Email Priority Scores — AI-scored email importance
// ---------------------------------------------------------------------------

export const emailPriorityScores = pgTable(
  "email_priority_scores",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** The email being scored (unique per email). */
    emailId: text("email_id").notNull().unique(),

    /** Priority score from 0 (ignore) to 100 (drop everything). */
    score: real("score").notNull(),

    /** Bucketed urgency level derived from the score. */
    urgencyLevel: urgencyLevelEnum("urgency_level").notNull().default("none"),

    /** AI-generated explanation of why this score was assigned. */
    reasoning: text("reasoning").notNull(),

    /** How important the sender is to this user (0-100). */
    senderImportance: real("sender_importance").notNull().default(50),

    /** Structured signals extracted from the email content. */
    contentSignals: jsonb("content_signals")
      .notNull()
      .$type<ContentSignals>()
      .default({
        hasDeadline: false,
        hasQuestion: false,
        hasMoneyConcern: false,
        hasActionRequired: false,
        mentionsAttachment: false,
        isReplyChain: false,
        threadLength: 1,
      }),

    /** What the AI predicts the user will do with this email. */
    predictedAction: text("predicted_action"),

    /** Confidence in the overall score (0.0-1.0). */
    confidence: real("confidence").notNull().default(0.5),

    scoredAt: timestamp("scored_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("eps_account_id_idx").on(table.accountId),
    uniqueIndex("eps_email_id_idx").on(table.emailId),
    index("eps_score_idx").on(table.score),
    index("eps_urgency_level_idx").on(table.urgencyLevel),
    index("eps_scored_at_idx").on(table.scoredAt),
  ],
);

// ---------------------------------------------------------------------------
// Relationship Insights — AI-derived contact relationship intelligence
// ---------------------------------------------------------------------------

export const relationshipInsights = pgTable(
  "relationship_insights",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** The contact email this insight is about. */
    contactEmail: text("contact_email").notNull(),

    /** Display name of the contact, if known. */
    contactName: text("contact_name"),

    /** Relationship strength score (0=stranger, 100=closest contact). */
    relationshipScore: real("relationship_score").notNull().default(50),

    /** When the user last exchanged emails with this contact. */
    lastContactedAt: timestamp("last_contacted_at", { withTimezone: true }),

    /** Average hours it takes this contact to reply. */
    avgResponseTimeHours: real("avg_response_time_hours"),

    /** How often this contact appears in the inbox. */
    emailFrequency: text("email_frequency").notNull().default("rare"),

    /** Overall sentiment of conversations with this contact. */
    sentiment: text("sentiment").notNull().default("neutral"),

    /** Top discussion topics with this contact. */
    topTopics: jsonb("top_topics")
      .notNull()
      .$type<string[]>()
      .default([]),

    /** True if this relationship is fading (no contact in 30+ days despite history). */
    fadingAlert: boolean("fading_alert").notNull().default(false),

    /** AI-suggested next action for this relationship. */
    suggestedAction: text("suggested_action"),

    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("ri_account_contact_idx").on(
      table.accountId,
      table.contactEmail,
    ),
    index("ri_account_id_idx").on(table.accountId),
    index("ri_relationship_score_idx").on(table.relationshipScore),
    index("ri_fading_alert_idx").on(table.fadingAlert),
    index("ri_updated_at_idx").on(table.updatedAt),
  ],
);

// ---------------------------------------------------------------------------
// Smart Replies — AI-generated reply suggestions per email
// ---------------------------------------------------------------------------

export const smartReplies = pgTable(
  "smart_replies",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** The email these replies are suggested for. */
    emailId: text("email_id").notNull(),

    /** Array of reply suggestions with confidence and tone. */
    replies: jsonb("replies")
      .notNull()
      .$type<SmartReplyOption[]>()
      .default([]),

    /** When these replies were generated. */
    generatedAt: timestamp("generated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    /** The reply text the user actually selected (null if none). */
    selectedReply: text("selected_reply"),

    /** Whether any suggested reply was actually used. */
    wasUsed: boolean("was_used").notNull().default(false),
  },
  (table) => [
    index("sr_account_id_idx").on(table.accountId),
    index("sr_email_id_idx").on(table.emailId),
    index("sr_generated_at_idx").on(table.generatedAt),
    index("sr_was_used_idx").on(table.wasUsed),
  ],
);

// ---------------------------------------------------------------------------
// Email Sentiments — AI-analyzed emotional tone of emails
// ---------------------------------------------------------------------------

export const emailSentiments = pgTable(
  "email_sentiments",
  {
    id: text("id").primaryKey(),
    /** The email analyzed. */
    emailId: text("email_id").notNull(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** Detected primary sentiment. */
    sentiment: emailSentimentEnum("sentiment").notNull().default("neutral"),

    /** Confidence in the classification (0.0-1.0). */
    confidence: real("confidence").notNull().default(0.5),

    /** Keywords that influenced the sentiment classification. */
    keywords: jsonb("keywords")
      .notNull()
      .$type<string[]>()
      .default([]),

    analyzedAt: timestamp("analyzed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("es_email_id_idx").on(table.emailId),
    index("es_account_id_idx").on(table.accountId),
    index("es_sentiment_idx").on(table.sentiment),
    index("es_analyzed_at_idx").on(table.analyzedAt),
  ],
);

// ---------------------------------------------------------------------------
// Writing Coach Results — AI scoring of draft emails
// ---------------------------------------------------------------------------

export const writingCoachResults = pgTable(
  "writing_coach_results",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** The draft email being scored (null for ad-hoc scoring). */
    emailId: text("email_id"),

    /** Clarity score (0-100). How easy is this email to understand? */
    clarityScore: real("clarity_score").notNull(),

    /** Tone score (0-100). How appropriate is the tone? */
    toneScore: real("tone_score").notNull(),

    /** Persuasiveness score (0-100). How compelling is the email? */
    persuasivenessScore: real("persuasiveness_score").notNull(),

    /** Specific improvement suggestions. */
    suggestions: jsonb("suggestions")
      .notNull()
      .$type<WritingCoachSuggestion[]>()
      .default([]),

    /** Overall letter grade: A/B/C/D/F. */
    overallGrade: text("overall_grade").notNull(),

    analyzedAt: timestamp("analyzed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("wc_account_id_idx").on(table.accountId),
    index("wc_email_id_idx").on(table.emailId),
    index("wc_overall_grade_idx").on(table.overallGrade),
    index("wc_analyzed_at_idx").on(table.analyzedAt),
  ],
);

// ---------------------------------------------------------------------------
// Predictive Actions — AI predictions of what user will do with an email
// ---------------------------------------------------------------------------

export const predictiveActions = pgTable(
  "predictive_actions",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),

    /** The email this prediction is about. */
    emailId: text("email_id").notNull(),

    /** What the AI predicts the user will do. */
    predictedAction: text("predicted_action").notNull(),

    /** Confidence in the prediction (0.0-1.0). */
    confidence: real("confidence").notNull().default(0.5),

    /** AI-generated explanation of why it predicted this action. */
    reasoning: text("reasoning").notNull(),

    /** What the user actually did (null until they act). */
    userAction: text("user_action"),

    /** Whether the prediction matched the actual action. */
    wasAccurate: boolean("was_accurate"),

    predictedAt: timestamp("predicted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("pa_account_id_idx").on(table.accountId),
    index("pa_email_id_idx").on(table.emailId),
    index("pa_predicted_action_idx").on(table.predictedAction),
    index("pa_was_accurate_idx").on(table.wasAccurate),
    index("pa_predicted_at_idx").on(table.predictedAt),
  ],
);

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const emailPriorityScoresRelations = relations(
  emailPriorityScores,
  ({ one }) => ({
    account: one(accounts, {
      fields: [emailPriorityScores.accountId],
      references: [accounts.id],
    }),
  }),
);

export const relationshipInsightsRelations = relations(
  relationshipInsights,
  ({ one }) => ({
    account: one(accounts, {
      fields: [relationshipInsights.accountId],
      references: [accounts.id],
    }),
  }),
);

export const smartRepliesRelations = relations(
  smartReplies,
  ({ one }) => ({
    account: one(accounts, {
      fields: [smartReplies.accountId],
      references: [accounts.id],
    }),
  }),
);

export const emailSentimentsRelations = relations(
  emailSentiments,
  ({ one }) => ({
    account: one(accounts, {
      fields: [emailSentiments.accountId],
      references: [accounts.id],
    }),
  }),
);

export const writingCoachResultsRelations = relations(
  writingCoachResults,
  ({ one }) => ({
    account: one(accounts, {
      fields: [writingCoachResults.accountId],
      references: [accounts.id],
    }),
  }),
);

export const predictiveActionsRelations = relations(
  predictiveActions,
  ({ one }) => ({
    account: one(accounts, {
      fields: [predictiveActions.accountId],
      references: [accounts.id],
    }),
  }),
);
